### ISSUE TITLE
Not available on the Linux platform 

### ISSUE THREAD

**Issue by Pillar1989** [edgeimpulse/integration-tests-firmware#1]
The installation looks fine, but it doesn't work. Is there something missing?  @janjongboom 

```
baozhu@bz:~/storage/integration-tests-firmware$ npm install 
audited 506 packages in 2.388s

26 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

baozhu@bz:~/storage/integration-tests-firmware$ ./node_modules/typescript/bin/tsc -p . &&     EI_USERNAME="xxx"     EI_PASSWORD="xxx"     EI_PROJECTNAME="xxx"     EI_HMACKEY="xxx"     EI_TESTWIFI=1     SELENIUM_WIFI_SSID="xxx"     SELENIUM_WIFI_PASSWORD="xxx"     ./node_modules/.bin/wdio wdio.headless.conf.js

Execution of 1 spec files started at 2020-06-03T09:26:51.196Z

2020-06-03T09:26:51.213Z INFO @wdio/cli:launcher: Run onPrepare hook
Could not find chromedriver in default path:  /home/baozhu/storage/integration-tests-firmware/node_modules/chromedriver/lib/chromedriver/chromedriver
Falling back to use global chromedriver bin
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: spawn chromedriver ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
    at onErrorNT (internal/child_process.js:415:16)
    [... lines matching original stack trace ...]
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
baozhu@bz:~/storage/integration-tests-firmware$ 



```

**Comment by janjongboom** [comment]
@Pillar1989 I think you need Chrome installed on the machine. Do you have that?
